name: CI Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-format:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.4
    - name: Initialize Terraform
      id: init
      run: terraform init
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

  terraform-validate:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.4
    - name: Initialize Terraform
      id: init
      run: terraform init
    - name: terraform validate
      id: validate
      if: (success() || failure())
      run: terraform validate

  tf-lint:

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
    - name: Chekout the Repo
      uses: actions/checkout@v4

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v3
    #   with:
    #     terraform_version: 1.14.4

    # - name: Initialize Terraform
    #   id: init
    #   run: terraform init


    # TFLint - Terraform Check
    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    # Setup TFLint
    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        github_token: ${{ secrets.CI_GITHUB_TOKEN }}

    # Print TFLint version
    - name: Show version
      run: tflint --version

    # Install plugins
    - name: Init TFLint
      run: tflint --init

    # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
    - name: Run TFLint
      run: tflint -f compact --recursive
